spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
    swagger-ui:
      enabled: true
openapi:
  service:
    title: Backend service
    version: v1.1.0
#    server: ${BACKEND-SERVICE:http://localhost:${server.post}}
    server: http://localhost:${server.port}
    api-docs: social media

jwt:
    secretKey: test123